import type { Metadata } from "next";

import "./globals.css";
import Head from "next/head";
import { ThemeProvider } from "@/components/theme-provider";



export const metadata: Metadata = {
  title: "moviehub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head />
    <body className="newFont dark:bg-black bg-white">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
    </body>
  </html>
  );
}
