import type { Metadata } from "next";

import "./globals.css";
import Head from "next/head";



export const metadata: Metadata = {
  title: "moviehub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Head>
          <link rel="icon" href="/Elipse tech.png"/>
        </Head>
      <body className="newFont">
        {children}
        </body>
    </html>
  );
}
